'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH onboard-settings 1 "Aug 2016" "Version 1.4.0" "X11 application"
.SH NAME
onboard-settings \- On-screen Keyboard (configuration dialog)
.SH SYNOPSIS
'nh
.fi
.ad l
\fBonboard-settings\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
\fBonboard-settings\fR is the configuration tool for \fBonboard\fI.

\fBonboard\fR  is an on-screen keyboard that can be useful for tablet PC
users, as well as  for mobility impaired people.
.PP
\fBonboard\fR supports macros, easy layout creation and word suggestion.

.SH "SEE ALSO"
\fB/usr/share/doc/onboard\fR
.SH AUTHOR
This manual has been written by
Mike Gabriel <mike.gabriel@das-netzwerkteam.de> and is distributed
under the GPL-3+ license.
