#!/usr/bin/python
# -*- coding: UTF-8 -*-

__copyright__ = "Copyright © 2009 Chris Jones"
__author__    = "Chris Jones <chrisejones@gmail.com>"

import sys

# Replace the default exception handler with one which handles chained
# exceptions.
from Onboard.Exceptions import chain_handler
sys.excepthook = chain_handler

from Onboard.OnboardGtk import OnboardGtk as Onboard
while True:
    ob = Onboard()
    if not ob.restart:
        break
