#!/usr/bin/python
# -*- coding: UTF-8 -*-

__copyright__ = "Copyright © 2007 Chris Jones"
__author__    = "Chris Jones <cej105@soton.ac.uk>"

import sys

if sys.argv[0].endswith('onboard-qt') == True:
    from Onboard.OnboardQt import OnboardQt as Onboard
else:
    from Onboard.OnboardGtk import OnboardGtk as Onboard

ob = Onboard()
