#!/bin/sh
set -e
# Automatically added by dh_desktop
if [ "$1" = "configure" ] && which update-desktop-database >/dev/null 2>&1 ; then
	update-desktop-database -q
fi
# End automatically added section
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall onboard
fi
# End automatically added section
