<?xml version="1.0"?>
<theme name="Ambiance" format="1.1">
    <color_scheme>Aubergine</color_scheme>
    <key_style>gradient</key_style>
    <roundrect_radius>30.0</roundrect_radius>
    <key_size>95.0</key_size>
    <key_fill_gradient>8.0</key_fill_gradient>
    <key_stroke_gradient>32.0</key_stroke_gradient>
    <key_gradient_direction>-4.0</key_gradient_direction>
    <key_label_font></key_label_font>
    <key_label_overrides></key_label_overrides>
</theme>
