<?xml version="1.0"?>
<theme name="Blackboard" format="1.1">
    <color_scheme>Black</color_scheme>
    <key_style>flat</key_style>
    <roundrect_radius>20</roundrect_radius>
    <key_size>95.0</key_size>
    <key_fill_gradient>30</key_fill_gradient>
    <key_stroke_gradient>70</key_stroke_gradient>
    <key_gradient_direction>-3</key_gradient_direction>
    <key_label_font>bold</key_label_font>
    <key_label_overrides></key_label_overrides>
</theme> 
