<?xml version="1.0"?>
<theme name="DarkRoom">
    <color_scheme>DarkRoom</color_scheme>
    <key_style>gradient</key_style>
    <roundrect_radius>20</roundrect_radius>
    <key_fill_gradient>4</key_fill_gradient>
    <key_stroke_gradient>22</key_stroke_gradient>
    <key_gradient_direction>2</key_gradient_direction>
    <key_label_font></key_label_font>
    <key_label_overrides></key_label_overrides>
</theme>
