#!/bin/bash

# Copyright © 2014, 2016 marmuta <marmvta@gmail.com>
#
# This file is part of Onboard.
#
# Onboard is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Onboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

XEMBED_SOCKET=tools/xembed_socket.py

( ${XEMBED_SOCKET} -x100 -y400 -s 1600x200 -t "Launched by gnome-screensaver" $(head -1 <(./onboard --xid --launched-by=gnome-screensaver)) ) &
PID1=$!
( ${XEMBED_SOCKET} -x100 -y700 -s 1600x200 -t "Launched by unity-greeter" $(head -1 <(./onboard --xid --launched-by=unity-greeter))) &
PID2=$!

sleep 0.2
${XEMBED_SOCKET} -x100 -y100 -s 1600x200 -t "Default" $(head -1 <(./onboard --xid))

kill $PID1 $PID2
wait $PID1 $PID2 2>/dev/null # no process termination messages

killall onboard

