#!/bin/sh

# Copyright © 2015 marmuta <marmvta@gmail.com>
#
# This file is part of Onboard.
#
# Onboard is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Onboard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

cp data/org.onboard.gschema.xml /usr/share/glib-2.0/schemas/

# optional: distro-specific customization
cp onboard-default-settings.gschema.override.example /usr/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override

glib-compile-schemas /usr/share/glib-2.0/schemas

